import { DevtoolsProvider } from "@providers/devtools";
import { useNotificationProvider } from "@refinedev/antd";
import { Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ColorModeContextProvider } from "@contexts/color-mode";
import { authProvider } from "@providers/auth-provider";
import { dataProvider } from "@providers/data-provider";
import "@refinedev/antd/dist/reset.css";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <body>
        <Suspense>
          <RefineKbarProvider>
            <AntdRegistry>
              <ColorModeContextProvider defaultMode={defaultMode}>
                <DevtoolsProvider>
                  <Refine
                    routerProvider={routerProvider}
                    dataProvider={dataProvider}
                    notificationProvider={useNotificationProvider}
                    authProvider={authProvider}
                    resources={[
                      {
                        name: "blog_posts",
                        list: "/blog-posts",
                        create: "/blog-posts/create",
                        edit: "/blog-posts/edit/:id",
                        show: "/blog-posts/show/:id",
                        meta: {
                          hide: true,
                          canDelete: true,
                        },
                      },
                      {
                        name: "categories",
                        list: "/product-categories",
                        create: "/product-categories/create",
                        edit: "/product-categories/edit/:id",
                        show: "/product-categories/show/:id",
                        meta: {
                          label: "Product Category",
                          parent: "Product",
                          canDelete: true,
                        },
                      },
                      {
                        name: "products",
                        list: "/products",
                        create: "/products/create",
                        edit: "/products/edit/:id",
                        show: "/products/show/:id",
                        meta: {
                          parent: "Product",
                          canDelete: true,
                        },
                      },
                      {
                        name: "machines",
                        list: "/machines",
                        create: "/machines/create",
                        edit: "/machines/edit/:id",
                        show: "/machines/show/:id",
                        meta: {
                          label: "Machines",
                          parent: "Machine",
                          canDelete: true,
                        },
                      },
                      {
                        name: "machine-products",
                        list: "/machine-products",
                        create: "/machine-products/create",
                        edit: "/machine-products/edit/:id",
                        show: "/machine-products/show/:id",
                        meta: {
                          label: "Products",
                          parent: "Machine",
                          canDelete: true,
                        },
                      },
                      {
                        name: "machine-sessions",
                        list: "/machine-sessions",
                        create: "/machine-sessions/create",
                        edit: "/machine-sessions/edit/:id",
                        show: "/machine-sessions/show/:id",
                        meta: {
                          label: "Active Sessions",
                          parent: "Sessions",
                          canDelete: true,
                        },
                      },
                      {
                        name: "session-histories",
                        list: "/session-histories",
                        create: "/session-histories/create",
                        edit: "/session-histories/edit/:id",
                        show: "/session-histories/show/:id",
                        meta: {
                          label: "Session Histories",
                          parent: "Sessions",
                          canDelete: true,
                        },
                      },
                    ]}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: "IV2Z6o-LY4QOq-WFglF8",
                    }}
                  >
                    {children}
                    <RefineKbar />
                  </Refine>
                </DevtoolsProvider>
              </ColorModeContextProvider>
            </AntdRegistry>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
